// opção para gerar automaticamente as sidebars com base na estrutura de diretórios dos seus documentos.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  areas: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

module.exports = sidebars;

// /** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
// const sidebars = {
//   docs: [
//     {
//       type: 'autogenerated',
//       dirName: '.',  // gera sidebar para todos os docs na pasta raiz
//     },
//   ],
//   areas: [
//     {
//       type: 'autogenerated',
//       dirName: 'areas', // gera sidebar para todos os docs na pasta 'areas'
//     },
//   ],
// };

// module.exports = sidebars;
