/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebarsAreas = {
  areas: [
    {
      type: 'autogenerated',
      dirName: '.', // gera sidebar para todos os docs na pasta raiz de 'areas'
    },
  ],
};

module.exports = sidebarsAreas;
